DELIMITER //

CREATE OR REPLACE DEFINER =  CURRENT_USER EVENT TableOpmitimizationJob 
STARTS  STR_TO_DATE(CONCAT(YEAR(CURRENT_DATE), '-', MONTH(CURRENT_DATE), '-', '01'), '%Y-%m-%d') + INTERVAL 23 HOUR
STARTS CURRENT_TIMESTAMP + INTERVAL 2 MINUTE
ON COMPLETION PRESERVE
ENABLE
DO CALL usp_TablesOptimization(12, 1000000);		

//
DELIMITER ;
